version: '2.2'

services:
  wallet:
    build: medium/service
    restart: on-failure
    stop_grace_period: 3s

    cpus: 0.1
    mem_limit: 128M
    memswap_limit: 128M
    pids_limit: 20

    ports:
      - 4386:7777

    ulimits:
      nofile:
        soft: 12000
        hard: 12000

  webapp:
    build: reallife/service
    restart: on-failure
    stop_grace_period: 3s

    cpus: 0.1
    mem_limit: 128M
    memswap_limit: 128M
    pids_limit: 20

    ports:
      - 4263:7777

    ulimits:
      nofile:
        soft: 12000
        hard: 12000
