version: '2.2'

services:
  sum:
    build: easy1/service
    restart: on-failure
    stop_grace_period: 3s

    cpus: 1.0
    mem_limit: 128M
    memswap_limit: 128M
    pids_limit: 512

    ports:
        - 41892:7777

    ulimits:
      nofile:
        soft: 12000
        hard: 12000

  simple_bo:
    build: easy2/service
    restart: on-failure
    stop_grace_period: 3s

    cpus: 0.1
    mem_limit: 128M
    memswap_limit: 128M
    pids_limit: 512

    ports:
        - 41488:7777

    ulimits:
      nofile:
        soft: 12000
        hard: 12000

  format_string:
    build: medium1/service
    restart: on-failure
    stop_grace_period: 3s

    cpus: 0.1
    mem_limit: 128M
    memswap_limit: 128M
    pids_limit: 512

    ports:
        - 26784:7777

    ulimits:
      nofile:
        soft: 12000
        hard: 12000

  mal:
    build: medium2/service
    restart: on-failure
    stop_grace_period: 3s
    privileged: true

    cpus: 1.0
    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 2048

    ports:
      - 17173:31337

    ulimits: 
      nofile:
        soft: 8192
        hard: 8192
