version: '2.2'

services:
  shamir:
    build: medium2/service
    restart: on-failure
    stop_grace_period: 3s

    ports:
      - 2386:7777

  elgamal:
    build: hard1/service
    restart: on-failure
    stop_grace_period: 3s

    cpus: 0.1
    mem_limit: 128M
    memswap_limit: 128M
    pids_limit: 20

    ports:
      - 2263:7777

    ulimits:
      nofile:
        soft: 12000
        hard: 12000
